from enum import Enum

class MessageType(Enum):
    PROPOSE = "PROPOSE"
    VOTE = "VOTE"
    ECHO = "ECHO"
    BLOCKCHAIN_REQUEST = "BLOCKCHAIN_REQUEST"
    BLOCKCHAIN_RESPONSE = "BLOCKCHAIN_RESPONSE"
    UNBLOCK_REQUEST = "UNBLOCK_REQUEST"